AllCops:
  Include:
  - '**/Gemfile'
  - '**/Rakefile'
  - '**/*.rake'
  - '**/*.gemspec'
  Exclude:
  - 'reference/**/*'
  - 'etc/**/*'
  - 'tmp/**/*'

Lint/FormatParameterMismatch:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  Enabled: false

Performance/StringReplacement:
  Enabled: true

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AlignHash:
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    inject: reduce
    collect: map
    find_all: select

# Allow comments to be aligned to one another.
Style/CommentIndentation:
  Enabled: false

# We like the truthiness operator.
Style/DoubleNegation:
  Enabled: false

# Style/DotPosition:
#   EnforcedStyle: trailing

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/ExtraSpacing:
  AllowForAlignment: true

Style/FormatString:
  EnforcedStyle: String#%
  SupportedStyles: String#%

# Style/GuardClause:
#   Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: false

# Style/RescueModifier:
#   Enabled: false

Style/RescueEnsureAlignment:
  Enabled: true

# We like terse methods.
Style/SingleLineMethods:
  Enabled: false

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
  - "="
  - "=>"
  - "||="
  - "+="
  - "-="
  - "*="
  - "/="

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
  SupportedStyles: comma
