---
common_username: &common_username "1234567890"
bridges:
  "Bridge-01":
    ip: "192.168.2.10"
    username: *common_username
    debug_hue: 0
  "Bridge-02":
    ip: "192.168.2.6"
    username: *common_username
    debug_hue: 25000
  "Bridge-03":
    ip: "192.168.2.7"
    username: *common_username
    debug_hue: 45000
  "Bridge-04":
    ip: "192.168.2.9"
    username: *common_username
    debug_hue: 12000
simulation:
  transition: 0.3
  sweep:
    length: 2.0
    # Ballpark estimation of Jen's palette:
    min:    48000
    max:    51000
  nodes:
    wave2:
      speed: [0.1, 1.0]
    perlin:
      speed: [0.1, 4.0]
    contrast:
      # Function: LINEAR, CUBIC, QUINTIC -- don't bother using iterations > 1
      # with LINEAR, as LINEAR is a no-op.
      function:   cubic
      iterations: 3
  controls:
    exit:
      position: mixer
      colors:
        "color": dark_gray
        "down":  white
    intensity:
      widget: Widgets::VerticalSlider
      positions:
      - [0, 2]
      - [1, 2]
      - [2, 2]
      - [3, 2]
      size: 6
      values:
      - [0.00, 0.00]
      - [0.00, 0.10]
      - [0.05, 0.20]
      - [0.15, 0.35]
      - [0.30, 0.60]
      - [0.50, 1.00]
      colors:
        "on":
        - 0x080010
        - 0x0D0019
        - 0x130023
        - 0x17002C
        - 0x1C0036
        - 0x22003F
        "off":
        - 0x020003
        - 0x030006
        - 0x050009
        - 0x07000D
        - 0x080010
        - 0x0A0013
        "down": 0x27103F
    saturation:
      widget: Widgets::HorizontalSlider
      positions:
      - [4, 2]
      - [4, 3]
      - [4, 4]
      - [4, 5]
      - [4, 6]
      - [4, 7]
      size: 4
      colors:
        "on":
        - 0x35303F
        - 0x28203F
        - 0x1C103F
        - 0x10003F
        "off":
        - 0x030304
        - 0x020204
        - 0x010104
        - 0x010004
        "down": 0x10103F
    spotlighting:
      x: 0
      y: 0
      mappings:
      # NOTE: Mappings defines the width/height of the widget implicitly!
      # NOTE: Values are indexes into main_lights array.
      #
      # Excluding outermost lights, and going top-down for left-most to
      # right-most light across left then right strings:
      #
      # Bridge 3/4:
      - [17, 18, 19, 20,   21, 22, 23, 24]
      # Bridge 1/2:
      - [ 3, 4, 5, 6,       7,  8,  9, 10]
      colors:
        "on":   0x272700
        "off":  0x020200
        "down": 0x3F3F10
# Main Lights is the group for which the main simulation will be applied.
# It can be any number of lights from any number of bridges but you'll need to
# plan groups out for saturation controls.
main_lights:
# Strip 1:
- ["Bridge-01", 38]
- ["Bridge-01", 37]
- ["Bridge-01", 36]
- ["Bridge-01", 26]
- ["Bridge-01", 17]
- ["Bridge-01", 19]
- ["Bridge-01", 35]

- ["Bridge-02", 12]
- ["Bridge-02", 14]
- ["Bridge-02", 13]
- ["Bridge-02", 11]
- ["Bridge-02", 15]
- ["Bridge-02", 18]
- ["Bridge-02", 19]

# Strip 2:
- ["Bridge-03", 8]
- ["Bridge-03", 2]
- ["Bridge-03", 3]
- ["Bridge-03", 4]
- ["Bridge-03", 7]
- ["Bridge-03", 5]
- ["Bridge-03", 6]

- ["Bridge-04", 7]
- ["Bridge-04", 10]
- ["Bridge-04", 6]
- ["Bridge-04", 5]
- ["Bridge-04", 9]
- ["Bridge-04", 8]
- ["Bridge-04", 1]
# TODO: Move four lights out of simulation, and into dance-floor group.
#
# TODO: Come up with appropriate behaviors/extensions of behavior for dance
# TODO: floor:
# TODO: * Spotighting.
# TODO: * Saturation.
# TODO: * Intensity.
#
# Dance Lights is the group of lights above the dance floor, which will get
# their own simulation, although updates will be interleaved with the main
# lights per-bridge.  It should be a positional map affording spatial
# coherence.
#
# For spotlighting/saturation/intensity purposes, it will be treated as one
# group.
dance_lights: []
accent_lights:
- ["Bridge-01", 9]
- ["Bridge-01", 10]
- ["Bridge-01", 11]
- ["Bridge-01", 12]
- ["Bridge-01", 13]
- ["Bridge-01", 33]
- ["Bridge-01", 34]
- ["Bridge-02", 7]
- ["Bridge-02", 8]
